App\Entity\Company:
  operations:
    ApiPlatform\Metadata\GetCollection:
      controller: App\Controller\GetCompanyController
    ApiPlatform\Metadata\Patch:
      controller: App\Controller\PatchCompanyController
